// action types

export const FETCH_USERS_API_CALL_REQUEST = 'FETCH_USERS_API_CALL_REQUEST'
export const FETCH_USERS_API_CALL_SUCCESS = 'FETCH_USERS_API_CALL_SUCCESS'
export const FETCH_USERS_API_CALL_FAILURE = 'FETCH_USERS_API_CALL_FAILURE'

export const USER_LIST_SET_PAGE = 'USER_LIST_SET_PAGE'
export const USER_LIST_SET_PAGE_SIZE = 'USER_LIST_SET_PAGE_SIZE'
export const USER_LIST_SET_SEARCH = 'USER_LIST_SET_SEARCH'
export const USER_LIST_SET_NEXT_SEARCH = 'USER_LIST_SET_NEXT_SEARCH'
export const USER_LIST_SET_OFFICE_LIST = 'USER_LIST_SET_OFFICE_LIST'
export const USER_LIST_SET_SORT = 'USER_LIST_SET_SORT'

export const FETCH_DETAILS_API_CALL_REQUEST = 'FETCH_DETAILS_API_CALL_REQUEST'
export const FETCH_DETAILS_API_CALL_SUCCESS = 'FETCH_DETAILS_API_CALL_SUCCESS'
export const FETCH_DETAILS_API_CALL_FAILURE = 'FETCH_DETAILS_API_CALL_FAILURE'

export const CLEAR_USER_DETAILS = 'CLEAR_USER_DETAILS'
export const CLEAR_ADDED_USER_DETAILS = 'CLEAR_ADDED_USER_DETAILS'
export const CLEAR_SAVE_ALERT = 'CLEAR_SAVE_ALERT'

export const FETCH_ACCOUNT_API_CALL_REQUEST = 'FETCH_ACCOUNT_API_CALL_REQUEST'
export const FETCH_ACCOUNT_API_CALL_SUCCESS = 'FETCH_ACCOUNT_API_CALL_SUCCESS'
export const FETCH_ACCOUNT_API_CALL_FAILURE = 'FETCH_ACCOUNT_API_CALL_FAILURE'

export const VALIDATE_NEW_USER_API_CALL_REQUEST = 'VALIDATE_NEW_USER_API_CALL_REQUEST'
export const VALIDATE_NEW_USER_API_CALL_SUCCESS = 'VALIDATE_NEW_USER_API_CALL_SUCCESS'
export const VALIDATE_NEW_USER_API_CALL_FAILURE = 'VALIDATE_NEW_USER_API_CALL_FAILURE'

export const FETCH_PERMISSIONS_API_CALL_REQUEST = 'FETCH_PERMISSIONS_API_CALL_REQUEST'
export const FETCH_PERMISSIONS_API_CALL_SUCCESS = 'FETCH_PERMISSIONS_API_CALL_SUCCESS'
export const FETCH_PERMISSIONS_API_CALL_FAILURE = 'FETCH_PERMISSIONS_API_CALL_FAILURE'

export const FETCH_OFFICES_API_CALL_REQUEST = 'FETCH_OFFICES_API_CALL_REQUEST'
export const FETCH_OFFICES_API_CALL_SUCCESS = 'FETCH_OFFICES_API_CALL_SUCCESS'
export const FETCH_OFFICES_API_CALL_FAILURE = 'FETCH_OFFICES_API_CALL_FAILURE'

export const FETCH_ROLES_API_CALL_REQUEST = 'FETCH_ROLES_API_CALL_REQUEST'
export const FETCH_ROLES_API_CALL_SUCCESS = 'FETCH_ROLES_API_CALL_SUCCESS'
export const FETCH_ROLES_API_CALL_FAILURE = 'FETCH_ROLES_API_CALL_FAILURE'

export const ADD_USER_API_CALL_REQUEST = 'ADD_USER_API_CALL_REQUEST'
export const ADD_USER_API_CALL_SUCCESS = 'ADD_USER_API_CALL_SUCCESS'
export const ADD_USER_API_CALL_FAILURE = 'ADD_USER_API_CALL_FAILURE'

export const SAVE_USER_DETAILS_API_CALL_REQUEST = 'SAVE_USER_DETAILS_API_CALL_REQUEST'
export const SAVE_USER_DETAILS_API_CALL_SUCCESS = 'SAVE_USER_DETAILS_API_CALL_SUCCESS'
export const SAVE_USER_DETAILS_API_CALL_FAILURE = 'SAVE_USER_DETAILS_API_CALL_FAILURE'

export const RESEND_REGISTRATION_EMAIL_API_CALL_REQUEST = 'RESEND_REGISTRATION_EMAIL_API_CALL_REQUEST'
export const RESEND_REGISTRATION_EMAIL_API_CALL_SUCCESS = 'RESEND_REGISTRATION_EMAIL_API_CALL_SUCCESS'
export const RESEND_REGISTRATION_EMAIL_API_CALL_FAILURE = 'RESEND_REGISTRATION_EMAIL_API_CALL_FAILURE'

export const HANDLE_INPUT_CHANGE = 'HANDLE_INPUT_CHANGE'

export const HANDLE_EMAIL_INPUT_CHANGE = 'HANDLE_EMAIL_INPUT_CHANGE'

export const HANDLE_DROPDOWN_CHANGE = 'HANDLE_DROPDOWN_CHANGE'

export const HANDLE_EDIT_BUTTON_CHANGE = 'HANDLE_EDIT_BUTTON_CHANGE'

export const HANDLE_CHECKBOX_CHANGE = 'HANDLE_CHECKBOX_CHANGE'
