// action types
export const FETCH_USERS_API_CALL_REQUEST = 'FETCH_USERS_API_CALL_REQUEST';
export const FETCH_USERS_API_CALL_SUCCESS = 'FETCH_USERS_API_CALL_SUCCESS';
export const FETCH_USERS_API_CALL_FAILURE = 'FETCH_USERS_API_CALL_FAILURE';

export const FETCH_DETAILS_API_CALL_REQUEST = 'FETCH_DETAILS_API_CALL_REQUEST';
export const FETCH_DETAILS_API_CALL_SUCCESS = 'FETCH_DETAILS_API_CALL_SUCCESS';
export const FETCH_DETAILS_API_CALL_FAILURE = 'FETCH_DETAILS_API_CALL_FAILURE';

export const FETCH_SEARCH_API_CALL_REQUEST = 'FETCH_SEARCH_API_CALL_REQUEST';
export const FETCH_SEARCH_API_CALL_SUCCESS = 'FETCH_SEARCH_API_CALL_REQUEST';
export const FETCH_SEARCH_API_CALL_FAILURE = 'FETCH_SEARCH_API_CALL_REQUEST';
