// action types
export const FETCH_USERS_API_CALL_REQUEST = 'FETCH_USERS_API_CALL_REQUEST';
export const FETCH_USERS_API_CALL_SUCCESS = 'FETCH_USERS_API_CALL_SUCCESS';
export const FETCH_USERS_API_CALL_FAILURE = 'FETCH_USERS_API_CALL_FAILURE';

export const FETCH_USER_DETAILS_API_CALL_REQUEST =
  'FETCH_USER_DETAILS_API_CALL_REQUEST';
export const FETCH_USER_DETAILS_API_CALL_SUCCESS =
  'FETCH_USER_DETAILS_API_CALL_SUCCESS';
export const FETCH_USER_DETAILS_API_CALL_FAILURE =
  'FETCH_USER_DETAILS_API_CALL_FAILURE';
